---
name: Pre-commit

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    uses: Baker-scripts/.github/.github/workflows/pre-commit.yml@24bddc386063122294bd55f4f965f2620ccb10c3 # main
