---
name: Pre-commit

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    uses: Baker-scripts/.github/.github/workflows/pre-commit.yml@aed3237f646a58922ada26b572ae67d67a6c9951 # main
